version: '3.8'

services:
    node:
        build:
            context: ./
            dockerfile: ./docker/node/Dockerfile
        container_name: ${APP_NAME}-node
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/app/
        networks:
            - backend
networks:
    backend:
        driver: bridge
